### ISSUE TITLE
Add kumavis as npm collaborator

### ISSUE THREAD

**Issue by kumavis** [ConsenSys/blockapps-web3#5]
@tcoulter `npm owner add kumavis`

**Comment by kumavis** [comment]
I am commandeering this vessel.
![image](https://cloud.githubusercontent.com/assets/1474978/10865737/0da9ffa0-7fd3-11e5-80fe-196f32c9d531.png)

**Comment by tcoulter** [comment]
Ahoy! Thar bidding be done.
